from enum import Enum

class OrchestratorPhase(str, Enum):
    VISION = "VISION"
    ROUTING = "ROUTING"
    ROADMAP = "ROADMAP"
    STORY = "STORY"
    SPRINT = "SPRINT"
    SPEC = "SPEC"

class OrchestratorState(str, Enum):
    # ROUTING
    ROUTING_MODE = "ROUTING_MODE"  # State 4

    # VISION PHASE
    VISION_INTERVIEW = "VISION_INTERVIEW"  # State 1
    VISION_REVIEW = "VISION_REVIEW"  # State 2
    VISION_PERSISTENCE = "VISION_PERSISTENCE"  # State 3

    # ROADMAP PHASE
    ROADMAP_INTERVIEW = "ROADMAP_INTERVIEW"  # State 5
    ROADMAP_REVIEW = "ROADMAP_REVIEW"  # State 6
    ROADMAP_PERSISTENCE = "ROADMAP_PERSISTENCE"  # State 7

    # STORY PHASE
    STORY_SETUP = "STORY_SETUP"  # State 8
    STORY_PIPELINE = "STORY_PIPELINE"  # State 9
    STORY_PERSISTENCE = "STORY_PERSISTENCE"  # State 10
    STORY_DETAILS = "STORY_DETAILS"  # State 20
    STORY_COMPLETE_DOC = "STORY_COMPLETE_DOC"  # State 19

    # SPRINT PHASE
    SPRINT_SETUP = "SPRINT_SETUP"  # State 11
    SPRINT_DRAFT = "SPRINT_DRAFT"  # State 12
    SPRINT_PERSISTENCE = "SPRINT_PERSISTENCE"  # State 13
    SPRINT_VIEW = "SPRINT_VIEW"  # State 14
    SPRINT_LIST = "SPRINT_LIST"  # State 15
    SPRINT_UPDATE_STORY = "SPRINT_UPDATE_STORY"  # State 16
    SPRINT_MODIFY = "SPRINT_MODIFY"  # State 17
    SPRINT_COMPLETE = "SPRINT_COMPLETE"  # State 18

    # SPEC PHASE
    SPEC_UPDATE = "SPEC_UPDATE"  # State 21
    SPEC_COMPILE = "SPEC_COMPILE"  # State 22
