from enum import Enum

class OrchestratorPhase(str, Enum):
    VISION = "VISION"
    ROUTING = "ROUTING"
    BACKLOG = "BACKLOG"
    ROADMAP = "ROADMAP"
    SPRINT = "SPRINT"  # Reserved for future implementation
    SPEC = "SPEC"

class OrchestratorState(str, Enum):
    # ROUTING
    ROUTING_MODE = "ROUTING_MODE"  # State 4

    # VISION PHASE
    VISION_INTERVIEW = "VISION_INTERVIEW"  # State 1
    VISION_REVIEW = "VISION_REVIEW"  # State 2
    VISION_PERSISTENCE = "VISION_PERSISTENCE"  # State 3

    # BACKLOG PHASE
    BACKLOG_INTERVIEW = "BACKLOG_INTERVIEW"  # State 23
    BACKLOG_REVIEW = "BACKLOG_REVIEW"  # State 24
    BACKLOG_PERSISTENCE = "BACKLOG_PERSISTENCE"  # State 25

    # ROADMAP PHASE
    ROADMAP_INTERVIEW = "ROADMAP_INTERVIEW"  # State 26
    ROADMAP_REVIEW = "ROADMAP_REVIEW"  # State 27
    ROADMAP_PERSISTENCE = "ROADMAP_PERSISTENCE"  # State 28

    # SPRINT PHASE (reserved for future implementation)
    SPRINT_SETUP = "SPRINT_SETUP"  # State 11
    SPRINT_DRAFT = "SPRINT_DRAFT"  # State 12
    SPRINT_PERSISTENCE = "SPRINT_PERSISTENCE"  # State 13
    SPRINT_VIEW = "SPRINT_VIEW"  # State 14
    SPRINT_LIST = "SPRINT_LIST"  # State 15
    SPRINT_UPDATE_STORY = "SPRINT_UPDATE_STORY"  # State 16
    SPRINT_MODIFY = "SPRINT_MODIFY"  # State 17
    SPRINT_COMPLETE = "SPRINT_COMPLETE"  # State 18

    # SPEC PHASE
    SPEC_UPDATE = "SPEC_UPDATE"  # State 21
    SPEC_COMPILE = "SPEC_COMPILE"  # State 22
