"""Constants for the story pipeline."""

# Session State Keys
KEY_STORY_DRAFT = "story_draft"
KEY_SPEC_VALIDATION_RESULT = "spec_validation_result"
KEY_REFINEMENT_RESULT = "refinement_result"
KEY_EXIT_LOOP_DIAGNOSTIC = "exit_loop_diagnostic"
KEY_VALIDATION_RESULT = "validation_result"
KEY_CURRENT_FEATURE = "current_feature"
KEY_PRODUCT_CONTEXT = "product_context"
KEY_AUTHORITY_CONTEXT = "authority_context"
KEY_SPEC_VERSION_ID = "spec_version_id"
KEY_RAW_SPEC_TEXT = "raw_spec_text"
KEY_FORBIDDEN_CAPABILITIES = "forbidden_capabilities"
KEY_USER_PERSONA = "user_persona"
KEY_STORY_PREFERENCES = "story_preferences"
KEY_REFINEMENT_FEEDBACK = "refinement_feedback"
KEY_ITERATION_COUNT = "iteration_count"

# Colors (ANSI)
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
MAGENTA = "\033[95m"
RESET = "\033[0m"
BOLD = "\033[1m"
DIM = "\033[2m"
